### ISSUE TITLE
精灵工坊研究笔记无法放入背包

### ISSUE THREAD

**Issue by N1ghtgl0w** [Nxer/Twist-Space-Technology-Mod#104]
gtnh240 tst0.3.4
精灵工坊在魔导书中点击获取研究笔记 会提示笔记已放入背包 但是实际无笔记产出 可以多次点击 会重复消耗纸和笔与墨耐久 仍然不会得到笔记

**Comment by Nxer** [comment]
@TheFlames096

**Comment by TheFlames096** [comment]
可以先/tc research @s BH_ELVEN_WORKSHOP（
晚上回去修bug

**Comment by TheFlames096** [comment]
已修复
