### ISSUE TITLE
comet not work

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#111]
i try to passive it the helium plasma on comet clyclotron but after i build it not being active and not start process

**Comment by horobo** [comment]
i try on my test world with space scaler and work

**Comment by Nxer** [comment]
Can you prepare some screenshot to describe what you do

**Comment by Nxer** [comment]
You need to troubleshoot the environment differences between the test and the main first

**Comment by horobo** [comment]
![immagine_2023-12-13_203114426](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/9cfccdf1-e790-482e-9f66-3cee22289a82)
![immagine_2023-12-13_203145670](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/890ff09b-4c97-4550-8002-8fbf9d96cbbc)
![immagine_2023-12-13_203155332](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/31fc9189-baed-4810-90a6-168c4efec759)
this is the comet and not work i try all mode

**Comment by horobo** [comment]
this is the space scaler 
![immagine_2023-12-13_204427015](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/eeb5eab1-2d47-4619-abde-dbb3746b2354)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/07ff7049-f040-4be3-b47c-ff8c9e21f022)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/2cb23188-65a3-4476-b512-824195940ada)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/5ca56568-3312-4568-9bfe-9bb2a71cc6c3)

**Comment by horobo** [comment]
I want to specify that the Comet doesn't turn on even though it said it was on

**Comment by Nxer** [comment]
a? I don't know what happened on GT++ Comet . I have not do anything about that machine.
Did comet can run normally in a vanilla GTNH environment ?

**Comment by horobo** [comment]
yes i farm passively unkown particels for quantum anomaly and this crafting not work

**Comment by Nxer** [comment]
> yes i farm passively unkown particels for quantum anomaly and this crafting not work

test this in a no tst GTNH 
and what version is your GTNH now and GT++ TST version

**Comment by horobo** [comment]
This thing is very funny but by putting an item in the stock, removing it and turning it on, the machine works, eliminating the bug that didn't make it start, so it solved itself -_-
