### ISSUE TITLE
mod bug

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#124]
after i install new version of mod,the pack doesnt read me mod and all multiblock controller has renamed with .name

**Comment by TheFlames096** [comment]
It's looked like you didnt successfully upgrade the mod.Do you have any extra infomation? Is the mod's items appeared in NEI?

**Comment by horobo** [comment]
i try with previuos version and not give me the problem
nope the item not showing on nei

**Comment by TheFlames096** [comment]
We just tested 0.3.6 but it's running fine.
Maybe you have downloaded a wrong file.
Try to redownload it and replace the old.

**Comment by TheFlames096** [comment]
Another possible reason
in early version this mod's id is called“GTNHcommunitymod” instead of TwistSpaceTechnology. Your blocks' data may have lost due to this.

**Comment by horobo** [comment]
i try with another world and work its all fine
