### ISSUE TITLE
集成矿处遗漏（？）

### ISSUE THREAD

**Issue by Goderium** [Nxer/Twist-Space-Technology-Mod#126]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/cacc75ca-21fd-4048-a19e-ec58c676322a)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/7a0149fa-9690-435a-8c87-7ab6491eb733)
这玩意也算矿石吧（）

**Comment by Nxer** [comment]
草

**Comment by Nxer** [comment]
#133  修了
