### ISSUE TITLE
巨型搅拌机通过样板处理总成处理灵魂沙时奔溃

### ISSUE THREAD

**Issue by DoUntilFalse** [Nxer/Twist-Space-Technology-Mod#129]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/22849379/ed83938e-eeac-461f-bf41-68b20121751e)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/22849379/acf5a985-350f-4436-a000-e6c8665d4ea2)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/22849379/d49001b6-7c06-4708-928a-b0d24beb8ae2)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/22849379/805af575-c4fb-4e2d-8f19-f8b6a46ae8bf)
TST版本号：0.3.3
GTNH版本号：2.4.0

**Comment by DoUntilFalse** [comment]
使用1号电路板也会崩溃

**Comment by Nxer** [comment]
日志呢？
现在版本已经0.3.6了

**Comment by Nxer** [comment]
虽然猜测应该是矿辞配方的问题，已经修了

**Comment by DoUntilFalse** [comment]
0.3.6确实正常了
