### ISSUE TITLE
计划列表 Things in plan

### ISSUE THREAD

**Issue by Nxer** [Nxer/Twist-Space-Technology-Mod#155]
### 机器 Machines
- [ ] 太阳能板工厂 Solar Panel Factory
- [ ] Miku发电机 Miku Generator
- [x] 巨型质量发生器：创世纪  Mega Mass Fabricator : Genesis
- [x] 灌装机与装罐机 Fluid Canner and Canning Machine
- [ ] 巨型原木拟生场 Mega Tree Growth Simulator
- [x] 大型中子活化器 Large Neutron Activator
- [ ] 巨龙之墓 Tomb of the Dragon
- [x] 进阶化学浸洗机
- [x] 大规模装配线暂时版 Mass Assemble Line (temp version)
- [x] 进阶巨型蒸馏塔 Advanced Mega Distillation Tower
- [x] 进阶巨型真空冷冻机 Advanced Mega Vacuum
- [x] 蒸汽木质homo之眼 Steam age wood EOH
- [x] 巨型熔炉 Mega Furnace
- [x] 真空冷冻机无线电网模式 Wireless Mode of Mega Freezer
- [x] 进阶纳米锻炉 Adv Nano forge
- [x] 巨型电弧炉 Mega Arc Furnace
- [x] 鬼泣5维吉尔的塑料椅子 DMC5 Vergil's plastic chair item
- [x] 无线算力网络
- [x] Debug未定元解析器
- [x] 大型粉碎机 - from ZPM to UEV
- [x] 巨型虚空采矿场 Mega Void Miner
- [x] 大型自动工作台 Mega Auto Crafter

### 杂项 Miscs

- [ ] 更新说明文件 Update README.md
- [ ] 为机器注册和配方注册添加配置文件控制是否在游戏内注册
- [ ] 生存用指令

**Comment by horobo** [comment]
uuh my idea :)

**Comment by ImgoodWK** [comment]
'深思'人工智能超算
根据提供电压直接获取巨量算力
tooltips:生命，宇宙及万物终极答案是42
(有典故，小说里人类为了拯救自己发明的超算，独自运算750万年后给人类的终极答案是42)

**Comment by AlotOfBlahaj** [comment]
考虑出台巨炽焰怎么样x

**Comment by Nxer** [comment]
> 考虑出台巨炽焰怎么样x

高炉系列已经有了

**Comment by ABKQPO** [comment]
有意向增加巨型合金炉吗，或者为神秘添加注魔仪式类机器

**Comment by Nxer** [comment]
> 有意向增加巨型合金炉吗，或者为神秘添加注魔仪式类机器

合金炉在计划上，神秘大概不会动

**Comment by ABKQPO** [comment]
流体加热器会有巨型机器吗，现在弄净化水太慢了

**Comment by Nxer** [comment]
> 流体加热器会有巨型机器吗，现在弄净化水太慢了

会有的

**Comment by ABKQPO** [comment]
目前有巨分子装配室的计划吗，对终极工作台的配方进行支持，目前梦魇工作台的速度太慢了

**Comment by Nxer** [comment]
> 目前有巨分子装配室的计划吗，对终极工作台的配方进行支持，目前梦魇工作台的速度太慢了

没有，AE兼容终极工作台的9×9合成分子装配室最好单独做成一个兼容附属mod

**Comment by xiaoACE6716** [comment]
有没有考虑过给精灵工坊加上精灵门交易的配方

**Comment by koiNoCirculation** [comment]
目前构思：大哥阵列
处理阵列升级版
支持256/1024/4096/无穷大并行（Int.MAX或者Long.MAX)
控制机器4级套娃，由处理阵列套上来
第1级预计uv解锁，第二级UEV，三级UMV，第四级是UXV解锁
计划支持所有单方块的处理机器和单方块发电机器（但愿吧）

**Comment by horobo** [comment]
I propose the idea of an improved dtpf where with different tiers of blocks it gives a discount on the cost of plasma for recipe

**Comment by pionxyz** [comment]
想到一个脑洞：奇点输入总成
打开后可以在里面放入数字奇点/流体奇点，放置不消耗的物品和编程电路板，设置优先级。链接ae后在ae看来类似驱动器，在机器看来直接读取奇点元件作为输入，用以输入超出2.1G的场景
