### ISSUE TITLE
astral quantum computer 

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#183]
after click on recipe/structure on nei game give me this log 
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/6ced0b86-2ddf-4903-bcaf-0591d4cdc0ac)

**Comment by Nxer** [comment]
@shordinger1  Maybe this fixed in 0.4.10

**Comment by horobo** [comment]
its 0.4.10

**Comment by Nxer** [comment]
OK I will check it
