### ISSUE TITLE
crystalline infinitier only takes normal energy hatches

### ISSUE THREAD

**Issue by CactusCool** [Nxer/Twist-Space-Technology-Mod#184]
is it intended that the crystalline infinitier only accepts normal and  regular amp wireless energy hatches, no laser or high amp wireless.

**Comment by Nxer** [comment]
No. All machine accepts all type of energy hatch. Check your hatch sets or re-place the controller block.

**Comment by CactusCool** [comment]
> No. All machine accepts all type of energy hatch. Check your hatch sets or re-place the controller block.

![2024-01-07_13 19 48](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/67992303/9f0e9992-4e7b-4657-be93-57c0edc929b5)
hmm it forms with umv wireless hatch but not 1,048k uiv laser
![Uploading 2024-01-07_13.19.55.png…]()

**Comment by CactusCool** [comment]
![Uploading 2024-01-07_13.19.55.png…]()

**Comment by CactusCool** [comment]
oh I figured it out its the glass, for some reason I cant put glass higher then the the tier of the stabilizer, so t2 stabilizer only forms with t2 glass. It means I cant put high tier energy hatches on it except regular bypasses I guess.

**Comment by Nxer** [comment]
> oh I figured it out its the glass, for some reason I cant put glass higher then the the tier of the stabilizer, so t2 stabilizer only forms with t2 glass. It means I cant put high tier energy hatches on it except regular bypasses I guess.

Use "Channel" to separate module tier setting.
