### ISSUE TITLE
拾荒者没有超净间环境

### ISSUE THREAD

**Issue by GuMingzi** [Nxer/Twist-Space-Technology-Mod#209]
无法执行净化水配方

**Comment by GuMingzi** [comment]
本想给拾荒者建一个超净间，但15*15的超净间放不下拾荒者。

**Comment by Nxer** [comment]
彳亍，我看看

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/d46605e6-eb4b-4d82-8902-84154a2e1aad)
恼
