### ISSUE TITLE
不可视之触无法超频

### ISSUE THREAD

**Issue by aekaDA** [Nxer/Twist-Space-Technology-Mod#213]
不可视之触部件装配线模式无法超频
![QQ浏览器截图20240126162722](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/138431240/02a8e92f-3c72-41af-b93e-751476d7901b)
版本：TwistSpaceTechnology-0.4.14-2.5.1fitted

**Comment by aekaDA** [comment]
![oo](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/138431240/40ec4f18-5995-4feb-9864-417c39e50cf9)
![123](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/138431240/d3020f8b-c3a0-44d8-bb3f-ebcb8887c04b)

**Comment by aekaDA** [comment]
改了cfg里的速度乘数也还是按nei显示的功率，时间处理

**Comment by Nxer** [comment]
再详细一点，从摆放仓室设备开始，描述到我可以尝试复现问题

**Comment by aekaDA** [comment]
1个传奇激光靶仓和1个2A MAX无线能源仓，样板输入总成，输出总线（me）

**Comment by aekaDA** [comment]
创造模式拿一组蓝图构造多方块结构

**Comment by Nxer** [comment]
啊，不超频，没事了，我修一下

**Comment by Nxer** [comment]
修了 #214
