### ISSUE TITLE
建议：给扭曲仪添加制作氰基丙烯酸乙酯的配方

### ISSUE THREAD

**Issue by InTheBackOf** [Nxer/Twist-Space-Technology-Mod#220]
输入：
* 配置电路=15 *0
* 碳粉 *41
* 氢气 *142,000
* 氧气 *41,000

输出：
* 氰基丙烯酸乙酯 *10,000

功率：UEV
时间：10s (200t)
需求炉温：11700k (无尽)

**Comment by Nxer** [comment]
#224  已添加
