### ISSUE TITLE
Question about dual input buffers

### ISSUE THREAD

**Issue by monroth** [Nxer/Twist-Space-Technology-Mod#235]
I found  two strange behaviors of dual input buffers. I suppose they are bugs.

1) Scenario: There are dual input buffers and normal input buses\hatches on same machine. If dual input buffers has something in them (for example, mold), they will disable regular input buses hatches, so they won't be used even if there is enough items for some recipe in them. That means that if you wanted to use dual input buses for 2-3 recipes with ball mold and regular input buses\hatches for ingot mold, you won't be able to, because ball mold will block ingots from forming

2) This is specific for fluid solidifiers, could not reproduce on other machines: if there is liquid in dual input hatch and mold in regular input bus outside, it will use liquid for this mold. I. E. at in case "liquid inside - mold in regular input bus outside" input separation is not working.

**Comment by Nxer** [comment]
Its Dual input hatch problem. The Crafting Input Buffer/Bus has the same problem. We can't fix it in TST. Wait the new GTNH version.
