### ISSUE TITLE
Draining empty dual input bus causes crash

### ISSUE THREAD

**Issue by starxingchenc** [Nxer/Twist-Space-Technology-Mod#241]
The updated dual input bus in 0.4.16 sometimes have ghost item:

![02WA3S}GISI85TH5S22$1QD](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/69507526/aa4130f6-0ba3-46a4-bb14-1f56ab424347)

The ghost item can be detected by Hologlasses and AE blocking mod, and will disappear when someone open the dual input bus.

When we try to fix this by auto putting and draining some unused fluid (use EIO pipes), the game and the save crashed.

[crash-2024-02-16_16.39.30-server.txt](https://github.com/Nxer/Twist-Space-Technology-Mod/files/14308671/crash-2024-02-16_16.39.30-server.txt)

**Comment by starxingchenc** [comment]
The crash to the save is permanent and whenever the server reboots,  it will shutdown by the same reason.

There might be a warning to this updated dual input bus since it is dangerous to the game save.

**Comment by Junyan721113** [comment]
```Java
return drain(ForgeDirection.UNKNOWN, new FluidStack(getFluid().getFluid(), maxDrain), doDrain);
```
When the first getFluid() returns null, it becomes null.getFluid(), causing crash.

**Comment by Junyan721113** [comment]
So check GT_MetaTileEntity_Hatch_DualInput.getFluid(), it could return null.

**Comment by starxingchenc** [comment]
#244
