### ISSUE TITLE
Wooden EOH?

### ISSUE THREAD

**Issue by AimaGod** [Nxer/Twist-Space-Technology-Mod#243]
When will the Wooden EOH be added? I'm so curious about it :(

**Comment by Nxer** [comment]
soooooooooooooooooooooon

**Comment by AimaGod** [comment]
Thx :) Btw: For which version is now TST? I'm still using 2.5.1 of GT:NH

**Comment by RhyVis** [comment]
We've got no idea on its functions... Maybe we need a discussion hub to gather more cooooool ideas

**Comment by AimaGod** [comment]
Shouldn't it be a steam powered or LV-MV-HV EOH with just a few materials like 1k-8k each cycle and some basic fluids like Oil, Salt Water and stuff like these? I mean, I was thinking about it idk

**Comment by Nxer** [comment]
> Shouldn't it be a steam powered or LV-MV-HV EOH with just a few materials like 1k-8k each cycle and some basic fluids like Oil, Salt Water and stuff like these? I mean, I was thinking about it idk

that's it, we have the same thinking

**Comment by Nxer** [comment]
#247

**Comment by AimaGod** [comment]
Oh, nice  then, hope it will come soon, I stopped my gt nh with twist run cause of this, I'm so curious

**Comment by Nxer** [comment]
#329
