### ISSUE TITLE
0417版本一个可能存在的小bug

### ISSUE THREAD

**Issue by ThickBlueberryJuice** [Nxer/Twist-Space-Technology-Mod#259]
我们在前几天更新了0417版本的tst，我在尝试用热能饕餮冻液态空气的时候出现了一些奇怪的现象
![D24FABE9137253857F56398E6CE889ED](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/d60cabe4-0da0-4689-a7da-723f6e5bc353)
![DC96C39153BE8BFA8C81E109F50C8A11](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/6576a1c3-ad10-4655-b796-2f3762425f9f)
在最开始，我给热能饕餮塞了十个无限进气仓，奇怪的是他并没有工作，我试过开关销毁，开关批处理，开关隔离，均没有作用
![4BEB6C7FC4FDAAA98B5418C3AE362E39](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/b3101a52-5d49-472b-8a66-18839084d46d)
简单询问群友后，群友也有点摸不着头脑
后面我简单尝试，将其中一个无限进气仓换成了原本就有的luv等级的超级进气仓
效果显著，现在热能饕餮读取了所有的进气仓，包括剩下的九个无限进气仓都读取了
![CE756ABD5AB2F047F98FEF834AD474B9](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/791e9bb8-3367-404d-bca1-8befa8fe4c9e)
![{DE97B3B3-50F5-4e21-B2E1-8CB8EDD11FD7}](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/b76f27c5-b1a9-40ef-be47-2628dcba83a4)
由于工作时间较快，有点难截图，这两张张图是进气仓里空气刚刚被冻完的截图，也表明热能饕餮此时正常工作了
而我将超级进气仓换回无限进气仓后热能饕餮又停止了工作，简单的控制变量
我不太确定这是bug还是特性，所以推一下issue

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/e519e863-5919-4196-af8d-87b7fc8b5c21)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/607e77a1-f790-4162-9f3a-daf9bcf2f190)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/6aad9cb6-ea93-46d9-8d0b-60f440a75870)


emmm，复现失败

**Comment by ThickBlueberryJuice** [comment]
在2024/2/28/晚，我们服务器的一位成员（群友杂鱼）在语音里对我说他可能也触发了这个bug
后来我们简单测试了一下，测试结果如下：
![QQ截图20240228193448](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/33964618-ef46-4433-ad57-3b21c836f9db)
这是一个热能饕餮。他的底部外围的防冻机械方块全部换成了无限进气仓，主机正上方的一个防冻机器方块换成了uxv104
很容易注意到这个热能饕餮并不在工作状态，这不是我抓timing截的图，而是他确实没在跑，这个原因是我将底部主机正对的防冻机械方块，也就是正后方中心的那个换成了me输出仓
![QQ截图20240228193723111](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/3394f642-fd07-4e9a-ac38-e9493e1e9ef9)
此时热能饕餮所有的舱室如下：
uxv104*1
无限进气仓若干
输出仓me*1

![QQ截图20240228193834222](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/377a61ac-d664-4cfd-b46a-793d5e8b7b59)
这是热能饕餮的主机设置，关闭隔离，打开销毁
此时热能饕餮的两个模式均不工作
![QQ截图20240228193945333](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/190b9cde-7c46-412f-8d19-11dfcc5cfb44)
而在这个基础上，进行操作：将me输出仓换成无限进气仓，即底部全为无限进气仓，没有输出仓，开销毁，此时热能饕餮正常工作
![QQ截图202402281940505555](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/b2e072e8-c2a0-4879-9e5e-0c39823723df)
在此基础上，再进行操作：在顶部的防冻机械方块中将其中一个换成me输出仓，并让主机重新检测结构使其成型
![QQ截图20240228194255666](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/125587349/4e85b1ab-da76-4301-ac7e-7e077aa84b8b)
可以看到此时热能饕餮正常工作，并且所冻的液态空气比之前的情况更多

我们仍不清楚这个bug是如何触发的，以及这个究竟是不是bug，但是我和杂鱼出现了同一种情况，也就是我描述的这种，或许这是一种可以复现的方式

**Comment by Nxer** [comment]
草，我还是没有复现，我单人档就给了一个进气仓和输出仓me，关了输入隔离开了锁配方和批处理，没开销毁，正常运行
