### ISSUE TITLE
1.25mega压缩问题

### ISSUE THREAD

**Issue by q2413274903** [Nxer/Twist-Space-Technology-Mod#27]
1.25中，mega压缩，不论是用普通遏制立场或是终极遏制立场，不论用的是激光仓还是无线仓或是普通能源仓，功率从zpm试到lv，主方块gui均显示机器崩溃
首先我下单了末影珍珠压缩块的单，后发现未完成，排查发现机器崩溃，我以为是输入问题，从buffer改成超级输入总线，仍然不行，后便逐一排查，均以失败告终。
后改换提取模式，此次未下单，仅点击开机便显示机器崩溃。
（不排除是我这边有什么没排查到，建议尝试）

**Comment by Nxer** [comment]
内部并行计算器报空指针的问题，和配方没什么关系
