### ISSUE TITLE
暂时无法使用NEI一键编写AE样板

### ISSUE THREAD

**Issue by Nxer** [Nxer/Twist-Space-Technology-Mod#3]
[crash-2023-10-30_16.20.27-client.txt](https://github.com/Nxer/GTNH_Community_Mod/files/13205246/crash-2023-10-30_16.20.27-client.txt)

**Comment by JodieRuth** [comment]
https://github.com/GTNewHorizons/bartworks/pull/350
看看这个？不一定有用，但是当时更新完马上解决了问题

**Comment by Nxer** [comment]
新的GTNH版本已经修了这个问题，但240没办法
