### ISSUE TITLE
星核钻机在漆黑世界会崩溃关机 Starcore Miner may crash in GC/GS dim or in DeepDark

### ISSUE THREAD

**Issue by Stulce** [Nxer/Twist-Space-Technology-Mod#314]
星核钻机目前在漆黑世界，以及某些星球貌似会出现BUG导致崩溃关机，或者无法开机。
![qhsj](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/163705656/0e301456-f130-4f69-8854-37d767bdebe7)
![qhsj hight](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/163705656/75f90aac-e11c-4684-a2aa-440d836ad944)
以上是在漆黑世界的表现，在漆黑世界地表放置星核钻机并且用64个全息投影构建之后的钻机深度达到的Y=18，符合Y<20的要求，但是出现崩溃。

![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/163705656/5c1485e0-6d3d-48a5-b139-5311f9f6f6ab)
以上是星核钻机在漆黑世界最底层放置的表现，主机内并未出现崩溃字样，而是无法开机。（我测试了土卫二，在地表放的，一样）

![(H`R_{}RSXO`$_5Q@XM U3P](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/163705656/b3c643ac-f527-4b6e-b46f-329ed2b90e1a)
以上是星核钻机在主世界的表现，正常运行。

**Comment by Stulce** [comment]
后续测试，在漆黑世界中把星核钻机贴住地底基岩层放置并且重启整个游戏后正常运行。（重启游戏后在漆黑世界地表放的钻机依旧显示结构不完整，并没有显示崩溃）莫名其妙 :D

**Comment by Nxer** [comment]
好了，这下乐了，我小虚采都出现问题了

**Comment by Nxer** [comment]
已于 GTNH 2.6.1 修复
