### ISSUE TITLE
无限晶胞共用情况下配方BUG

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [Nxer/Twist-Space-Technology-Mod#318]
完美能量水晶的配方和反应釜的能量水晶冲突，多台机器共用一个的结构下造完美能量水晶会变成IC2的能量水晶
![屏幕截图 2024-03-20 053027](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/eaeebc7e-b9e7-41a7-8d73-67ba262badb5)
![屏幕截图 2024-03-20 052714](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/688ef553-f06e-4d03-898e-b1a569f862c5)

**Comment by Nxer** [comment]
个人操作问题

**Comment by NNNNMMMMIIII** [comment]
两台无限晶胞共用一个结构，一个晶胞模式一个反应釜模式，如果把完美能量水晶配方放进去，那有概率变成制作IC能量水晶

**Comment by Nxer** [comment]
> 两台无限晶胞共用一个结构，一个晶胞模式一个反应釜模式，如果把完美能量水晶配方放进去，那有概率变成制作IC能量水晶

不能把输入分开吗？

**Comment by NNNNMMMMIIII** [comment]
不能，外面只能放能源仓样板输入仓只能放里面，然而2个主机都会共同检测，结果反应釜那边的配方和晶胞的配方重叠了

**Comment by Nxer** [comment]
> 不能，外面只能放能源仓样板输入仓只能放里面，然而2个主机都会共同检测，结果反应釜那边的配方和晶胞的配方重叠了

![9XSUKH0@%H4K8HF@)XZIBBV](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/58a3a040-cbfb-4578-84d9-a673744de035)
真的不能吗

**Comment by NNNNMMMMIIII** [comment]
![屏幕截图 2024-03-20 183221](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/9550940b-c8e1-4db5-a118-1e149c2cf154)

**Comment by Nxer** [comment]
哦，我知道了。
你没有用随意放置仓室的“特性”，那没办法，只能多造一台了。

**Comment by NNNNMMMMIIII** [comment]
原来能放的，别投影骗了

**Comment by Nxer** [comment]
是设计上不考虑共用，共用属于玩家考虑的部分。仓室任意放置属于特性，或者也可以算作bug
