### ISSUE TITLE
Is the exploding cleanroom intentional?

### ISSUE THREAD

**Issue by Glowpride** [Nxer/Twist-Space-Technology-Mod#324]
The clean-room added by Twist-Space explodes catastrophically when any blocks are broken while the machine is in pass-power mode (even if the machine is turned off). 

Is this behavior intentional? It does not seem to replicate with the GT clean-room.

**Comment by ValueTown1** [comment]
I have also confirmed that this occurs and would like this changed/fixed.

**Comment by Nxer** [comment]
It's correct. It's an Active Transformer at the same time, will explode like other TecTech machines.

**Comment by Glowpride** [comment]
Whelp that explains a lot. I guess we should have known that because of the power-pass interface... I still think there should be a mention to that fact in the tool-tip. and maybe a warning that it explodes if broken while running on it like on the active transformer.

**Comment by Nxer** [comment]
will do
