### ISSUE TITLE
Mega 进阶装配线

### ISSUE THREAD

**Issue by JodieRuth** [Nxer/Twist-Space-Technology-Mod#35]
如果你不想在游戏后期来上不知道多少进阶装配线，然后再用卡出天际的数据库串联它们，你就需要mega进阶装配线。

至少保留装配线的读取配方特色+可以超到1t往后+超级大的闪存槽位+没有愚蠢的激光超频

至少UMV-UXV开放制造

**Comment by Nxer** [comment]
不如放弃装配线，机械装配太落后啦

**Comment by Nxer** [comment]
装配线作为游戏性的重要一环其性能代价是难以平衡的。如果用简单机器代替的话如何进行设置我还没什么思路，所以一直没做。

**Comment by Nxer** [comment]
所以我尽可能的把能从装配线配方里拆出来的功能拆出来了

**Comment by JodieRuth** [comment]
> 装配线作为游戏性的重要一环其性能代价是难以平衡的。如果用简单机器代替的话如何进行设置我还没什么思路，所以一直没做。

蓝框岩浆做主机，名字叫什么寰宇装配之类的乱七八糟玩意，合成表里写个高算力5就说他很聪明能自己识别所有闪存的配方物品摆放顺序，至于闪存这是游戏特色不得不品鉴

**Comment by Nxer** [comment]
可能我可以在大电装的另一个模式做做文章

**Comment by JodieRuth** [comment]
> 可能我可以在大电装的另一个模式做做文章

没有读取闪存的装配线就像没有激光的源神一样 失去了灵魂。不管怎么说，闪存虽然很蠢，但是这是贯穿gtnh的特色
