### ISSUE TITLE
matter state convertor

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#368]
matter state convertor doesnt see the reciper for fluid extractor 
![immagine_2024-04-05_010018397](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/9e9cd172-7947-4cf3-ac1a-7fe5d77843cb)
![immagine_2024-04-05_010031159](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/32335126/a709f286-195c-4c9c-a24f-583f078abffc)

**Comment by Nxer** [comment]
![7)T23{ YVGC LLZ `}D{JY3](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/2a3d51f8-d271-44b8-8af8-dfb4713238f4)
seems someone make a mistake in NEI Handler

**Comment by Nxer** [comment]
wait, what your version

**Comment by horobo** [comment]
last one

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/3db8fcda-43ae-48d1-b12b-f3523df4be79)
I can't catch this exception

**Comment by Nxer** [comment]
uh, I know what is error

**Comment by Nxer** [comment]
#373  fixed
