### ISSUE TITLE
无线主光学和副光学无法制作

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [Nxer/Twist-Space-Technology-Mod#370]
大规模和精密都不行，都是有电有材料有电路板
![屏幕截图 2024-04-06 111608](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/4de29236-46d0-46b1-be57-90cdae62cf0e)
![屏幕截图 2024-04-06 111654](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/31f9c56e-03c7-4b69-b512-517d1821cb9b)
![屏幕截图 2024-04-06 111849](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/b5d113ef-a1ed-4bf0-a489-deb57563cc86)

**Comment by Nxer** [comment]
什么版本，我这儿未出现这个问题

**Comment by NNNNMMMMIIII** [comment]
0.4.27版本，大概是量子增幅器的锅，没办法叠加然后就放不下合成表了
![Uploading 屏幕截图 2024-04-06 171357.png…]()

**Comment by Nxer** [comment]
组装机配方速推这边没问题，扫配方时不影响。装配线用存储输入总线。
