### ISSUE TITLE
[BUG] 无线算力网络升级芯片配方不可堆叠

### ISSUE THREAD

**Issue by Dawnwalker666** [Nxer/Twist-Space-Technology-Mod#371]
版本0.4.27-2.5.1fitted，jre1.8.0_281，forge 10.13.4.1614，GTNH版本2.5.1。
仔细来讲，不算bug。无线算力网络升级芯片做了好久，终于等到了。结果吧。。配方长成这个样子的：
![图片](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/49862610/f0369bd5-137f-4dd2-b323-5ba481347805)
但是问题在于，第1234号的量子无线增幅器是不可堆叠的。可能是这个配方是鼓励装配线使用存储输入？由于其不可堆叠，传统的ULV输入总线是无法做到像配方这样堆叠输入的。

**Comment by Dawnwalker666** [comment]
另外一个小瑕疵是。工业注魔矩阵在输入某些不相干的配方会显示内部错误。如下图：
![图片](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/49862610/4e620f04-b506-4cf5-ab95-6a142bcd4045)
如图是输入了创世碎片的原料，但是不知道是哪里的问题。但后来我们才发现是因为游戏内的NEI并没有显示创世碎片有工业注魔矩阵的配方。问题在于，若该配方本不存在，则主机应该不会有反应。个人猜想或许是批量生成配方时该配方生成错误等等？

**Comment by Nxer** [comment]
是的，用存储输入总线进行操作。私货特有的偷偷藏屎。

**Comment by xiaoxing2005** [comment]
> 另外一个小瑕疵是。工业注魔矩阵在输入某些不相干的配方会显示内部错误。如下图： ![图片](https://private-user-images.githubusercontent.com/49862610/320225205-4e620f04-b506-4cf5-ab95-6a142bcd4045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTA2MzEsIm5iZiI6MTcxMjQ5MDMzMSwicGF0aCI6Ii80OTg2MjYxMC8zMjAyMjUyMDUtNGU2MjBmMDQtYjUwNi00Y2Y1LWFiOTUtNmExNDJiY2Q0MDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExNDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYjhlYWE5MDQ1MGM4OWU5Njg5NDlmY2NlZTc3ODdkZTc0YjBjYjExM2EyNDE4ZGZlNDRjNDgxZjUwNjE2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxRdBaqCoAozCA_1QGCe8aV0jLsQ21CDrHO1BK29n-0) 如图是输入了创世碎片的原料，但是不知道是哪里的问题。但后来我们才发现是因为游戏内的NEI并没有显示创世碎片有工业注魔矩阵的配方。问题在于，若该配方本不存在，则主机应该不会有反应。个人猜想或许是批量生成配方时该配方生成错误等等？

报错误是因为用了buffer，buffer有个特性是别的样板找到了配方而当前的样板输入了物品但找不到配方就会报内部错误,另外配方问题会在下次更新修复。
