### ISSUE TITLE
【bug】武德之眼

### ISSUE THREAD

**Issue by QianWJ411** [Nxer/Twist-Space-Technology-Mod#379]
武德之眼出现了崩溃，拆掉控制器重新放置仍然显示崩溃
![QQ图片20240408222812](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/87937433/0a4e6fb5-642f-4bcc-aca7-b9ad1c1b466a)

**Comment by QianWJ411** [comment]
![QQ图片20240408222812](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/87937433/d460b627-ee0a-426d-80c1-dc30d4d2fc72)

**Comment by Nxer** [comment]
后台日志呢，也可能是虚采同款bug

**Comment by QianWJ411** [comment]
咋看啊，服务器里的

**Comment by Nxer** [comment]
触发崩溃后看后台的报错信息
