### ISSUE TITLE
一些疑问和建议

### ISSUE THREAD

**Issue by a5632645** [Nxer/Twist-Space-Technology-Mod#400]
1. 请问能否添加一个增加光子掌握者并行的芯片或者其他类似物品？256并行对比其他机器有点低，只能等umv无损或者加激光或者堆光刻机
2. 无线算力网络不支持玩家共享，也没有指令能够共享，有没有什么解决方案
3. 无线算力网络使用权重的话有点难分配，能否使用具体数值来提供输出算力？
4. 有没有计划出电聚爆，pcb工厂的TST机器

**Comment by Nxer** [comment]
- 1.  有无损超频配合批处理基本不需要额外处理并行，可以考虑在无损超频同时把并行设置为2.1G。
 - 2. 无线算力网络与戴森球系统共享同一队伍系统。
 - 3. 无线算力输入仓右键打开GUI进行设置，若算力充足则全部无线算力输入仓获得GUI内设置的算力输入，算力不足则输入值视为请求权重进行算力分配。
 - 4. 电聚爆有计划，PCB工厂没有。或者说，有无损超频+激光仓支持=不需要升级版本机器/没有性能压力。
