### ISSUE TITLE
埃克化工厂似乎不能识别输入总成的流体

### ISSUE THREAD

**Issue by Windorain** [Nxer/Twist-Space-Technology-Mod#402]
在化工厂四种方块正确放置且成型的情况下，化工厂可以识别输入总成的虚拟电路板和物品，但似乎不能正确识别流体。
举例：Rp-1燃料需要液氧和rp-1，输入总成可以识别内部的虚拟电路板1，但不能正确识别内部的流体。将其转移到其他的输入仓可正确识别。

版本：2.5.1
mod版本：0.4.29

**Comment by Nxer** [comment]
输入总成的问题，放样板仓一样不识别，等更新2.6
