### ISSUE TITLE
球状闪电功率bug

### ISSUE THREAD

**Issue by nanmumc** [Nxer/Twist-Space-Technology-Mod#411]
功率被限制在能源仓等级,图中使用[压4线圈],[海珀珍线圈],[无尽强化玻璃],[卓越力场]
采用1024A UHV激光功能,球闪开启聚变模式,功率被限制在1aUHV
若采用64A UMV无线能源仓,则功率被限制在1aUMV

![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/25528572/6a7d7c55-6061-411a-b9ac-9e623b5d2882)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/25528572/0b1e3ca4-fab3-4a70-8750-e4b5ec29c793)

另外,实际使用中,玻璃等级限制了配方等级,这一点没有在NEI里说明
还有,生存模式建造外环一次只放25个方块,外环可是有1w方块啊

GTNH 2.6.0 
TST 0.4.29

更新:
我翻了代码,问题可能出在 `src/main/java/com/Nxer/TwistSpaceTechnology/common/machine
/TST_BallLightning.java` 307行

```
302           if (isWirelessMode || FusionMaxEut < getMaxInputEu()) {
303                logic.setAvailableVoltage(FusionMaxEut);
304                logic.setAvailableAmperage(1);
305                logic.setAmperageOC(false);
306            } else {
307                super.setProcessingLogicPower(logic);
308            }
```

当FusionMaxEut < getMaxInputEu()这个判断能过的时候机器正常,
即用UHV 262,144激光仓可以达到机器max功率

**Comment by Nxer** [comment]
修了，应该  #408

**Comment by nanmumc** [comment]
okk,那close了吧
