### ISSUE TITLE
Tower Of Abstraction Issues

### ISSUE THREAD

**Issue by FrostyFire1** [Nxer/Twist-Space-Technology-Mod#413]
# General info
### Twist Space Technology version: 0.4.29

# The Bugs
### The multiblock does not generate power until you either quit and rejoin the save (singeplayer) or restart the server (multiplayer).
When the multiblock is initially placed and turned on it runs normally but doesn't generate any power.
![2024-05-04_19 39 50](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/66720515/e3e5ed19-ff11-46c1-8e8e-24da16bb9aff)
![2024-05-04_19 39 32](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/66720515/2c17e799-db96-4379-a772-6e34d8f3064e)

Getting to maximum efficiency makes no difference. (For this multi the first layer of eggs has been replaced with infinity eggs)

![2024-05-04_20 08 59](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/66720515/95211154-182d-462d-a4cd-5adce2cee293)

![2024-05-04_20 09 02](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/66720515/b8c477af-82d6-4ff3-88eb-81ebf4d26bd7)

This behavior is consistent with all dynamo hatch types (TecTech, Normal and Laser). 
Things that i've tried to make the multi behave normally:
- Breaking and replacing the controller
- Turning off the controller, toggling power pass and turning it back on
- Turning off the controller, then turning it on again
- Replacing the dynamo hatch
- Placing a different dynamo hatch
- Placing the dynamo hatch in a different casing

**However, a few seconds after quitting and rejoining the save the dynamos started producing power.**
![2024-05-04_19 49 02](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/66720515/b8455e14-13a4-4993-a534-da6c07615100)

### The multiblock tooltip
The Tower Of Abstraction claims that the warm-up process takes about 500 seconds.
![2024-05-04_19 50 14](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/66720515/27544c8e-c209-49fa-8ac5-adb60732e9ed)

The warm up time is actually #based on the maximum efficiency of the multiblock and the amount of infinity eggs present. Without infinity eggs, the warm-up time takes at least 10000 seconds (nearly 3 hours!). Every infinity egg raises the efficiency increase (Which by default is 0.01%) by an entire percentage point.

Relevant code snippet: 
https://github.com/Nxer/Twist-Space-Technology-Mod/blob/8fa56b8e6199677e23a1e9e2b9495e1f8db6f962/src/main/java/com/Nxer/TwistSpaceTechnology/common/machine/GT_TileEntity_MegaEggGenerator.java#L89C1-L93C6

**Comment by Nxer** [comment]
@RhyVis

**Comment by RhyVis** [comment]
Looking into it

**Comment by Taskeren** [comment]
@FrostyFire1 
Test it in the latest version (0.5.9).

I cannot reproduce the problem that the machine won't generate power until rejoining.
The machine now increase the efficency properly as the tooltip mentioned.

**Comment by FrostyFire1** [comment]
@Taskeren it appears that #599  fixed the issue. The multiblock forms, turns on and generates power properly without having to do anything.
