### ISSUE TITLE
梦魇工业合成中心tooltip问题

### ISSUE THREAD

**Issue by SafariXiu** [Nxer/Twist-Space-Technology-Mod#419]
![QQ截图20240512144211](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/98251218/dd15b559-7292-436c-b11e-28f40125c541)
tooltip不能说是言简意赅，也能说是问题百出了(
快改改罢 总线变成了仓，也没有说这东西主机要连接到ME线缆才能用zzz

**Comment by Nxer** [comment]
@shordinger1
