### ISSUE TITLE
Cannot Load Recipe Previews in GTNH 2.6.0

### ISSUE THREAD

**Issue by Vampurrya** [Nxer/Twist-Space-Technology-Mod#422]
Hello, whenever I try to look up any recipe from Twist Space in NEI, I receive an error. I can see the recipe to make the machines, but cannot see any previews or how to build them. Only Twist Space has this issue.

![2024-05-17_07 56 12](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/170100787/8371b3c8-274e-4845-961c-9c34cd7c7011)

![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/170100787/01b2dc78-8e07-4f05-8179-56c3b2718ec5)

**Comment by Jason-Alpha** [comment]
I have a same problem,maybe we need to wait TST update for GTNH 2.6.0

**Comment by Nxer** [comment]
You are using TST 2.5.1 fitted version, so it should crash.
