### ISSUE TITLE
[BUG]疑似未加载区块导致分子解构器片数检查阻塞

### ISSUE THREAD

**Issue by HakureiHikaze** [Nxer/Twist-Space-Technology-Mod#424]
**GTNH版本：** 2.6.0 (更新了AE2版本，但应该不影响)
**TST版本：** 0.4.29
_已查阅既往issue_

Heap Dump如下（限于磁盘空间，只做了两个Heap Dump，发现线程阻塞在分子解构器的piece检查上，且piece并非预期值，而是增长的巨大值，此为第二个）：
![672c9e1e26382ff29e8b858e37a50c3a](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/26541806/78e89a3a-0ddd-4c6f-b5d2-22892ee165a9)

推测是某种原因（也许是未加载区块？）导致GT_TileEntity_MoleculeDeconstructor:139处的判断条件始终为true，导致无法跳出循环。

**Comment by Nxer** [comment]
是的，手动加载区块就可以了。 TST机器没有做自动区块加载功能。
