### ISSUE TITLE
放置通用电路板转换器导致崩溃

### ISSUE THREAD

**Issue by salieelinar** [Nxer/Twist-Space-Technology-Mod#427]
放置通用电路板转换器的主方块就会崩溃，无法进入游戏，只能回档

https://pastebin.ubuntu.com/p/Y4Kkc4ttRG/

`ava.lang.NoSuchMethodError: com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase$1.setMaxParallelSupplier(Ljava/util/function/Supplier;)Lgregtech/api/logic/ProcessingLogic;
    at com.Nxer.TwistSpaceTechnology.common.machine.multiMachineClasses.GTCM_MultiMachineBase.createProcessingLogic(GTCM_MultiMachineBase.java:87)`

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/8d6524eb-2b52-431c-86a1-26cc9a65e6dd)

你不是第一个把 2.5.1专用版本TST塞到GTNH2.6.0的猪鼻，也不会是最后一个（恼

**Comment by salieelinar** [comment]
我是猪= =
