### ISSUE TITLE
工业梦魇没有无尽箱子配方

### ISSUE THREAD

**Issue by SafariXiu** [Nxer/Twist-Space-Technology-Mod#428]
![408d3b8c3d84d046c2133aa105e692df](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/98251218/2f29de54-c701-499a-9eaa-a6d575022bfa)
似乎缺少了配方 在转换配方里面也查不到 大机器也识别不到这个配方

**Comment by Nxer** [comment]
@shordinger1

**Comment by Nxer** [comment]
已修复
