### ISSUE TITLE
星核钻机在漆黑世界以及主世界不工作 GTNH2.6.1 JAVA17.0.10

### ISSUE THREAD

**Issue by shaqian150** [Nxer/Twist-Space-Technology-Mod#429]
星核钻机在漆黑世界以及主世界不工作（只测试了这两个）
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/103816803/c1152a04-d0dc-4d99-8870-076e2077dac3)
会闪一下这个界面后就自动关机了

GTNH2.6.1 JAVA17.0.10
添加mod
boxplusplus-1.7.5
NotEnoughCharacters-1.7.10-1.5.2
TwistSpaceTechnology-0.4.29
VeinMiner-1.7.10-0.36.0.496+28a7f13

WIN11 启动器PRISM

**Comment by Nxer** [comment]
暂时未适配GTNH-2.6.1  等下个月TST的更新吧

**Comment by Nxer** [comment]
已于 GTNH 2.6.1 修复
