### ISSUE TITLE
通用电路板转换器转换LV和HV电路板有点问题

### ISSUE THREAD

**Issue by doctormdkzrp** [Nxer/Twist-Space-Technology-Mod#430]
游戏版本:2.6.0
java版本：java 8 

问题描述：LV/HV电路板转换过程有问题，会转换成<电路板>和<高级电路板>。其他的电路板没问题。

可能得原因是：2.6.0的LV和HV的通用电路板没有矿物词典……

我不太清楚是不是应该在这里发issues……
![微信截图_20240530224633](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/31733877/b4505840-9338-4d0f-b6af-132cf9b12797)
![微信截图_20240530224645](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/31733877/efc7af34-e331-4eaa-95f8-9f541ec235b6)
![微信截图_20240530224658](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/31733877/ea6065d8-dd6c-4adc-91a9-a58cde9064c8)

**Comment by Nxer** [comment]
你可以掏一个LV通用电路板和HV电路板出来看看他们到底通用不通用
