### ISSUE TITLE
不可视之触bug

### ISSUE THREAD

**Issue by RiderisPr** [Nxer/Twist-Space-Technology-Mod#471]
不可视之触：部件装配线无线电网模式下无法运行，使用部件装配线时会显示shut down due to power loss，硼玻璃部件装配外壳均为umv，电网中电有22位，制作lv马达也会这样。

**Comment by RiderisPr** [comment]
![QQ截图20240613210353](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/114299480/a8c1080d-4b2d-4c71-92da-58eb10d04184)

**Comment by Nxer** [comment]
看一眼log有输出什么吗？

拆掉主机重放还会复现bug吗？

什么版本？

**Comment by RiderisPr** [comment]
log，不会查看；拆掉主机仍然存在，但是更换成无限能源仓后可以使用；版本号2.6.1

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/a9c33201-c4c2-455d-a8b2-246593c1c23a)


未成功复现bug

**Comment by Nxer** [comment]
Shut down due to power loss.

这是跳电了，你怕不是有地方塞了能源仓你不知道吧。

如果拆除全部能源仓的话，waila会提示你 机器已进入无线电网模式。自己排查吧

**Comment by RiderisPr** [comment]
好的，我排查一下。

**Comment by RiderisPr** [comment]
已正常使用，误报bug了

**Comment by RiderisPr** [comment]
已正常使用，误报bug了
