### ISSUE TITLE
巨型装配线不支持兰博顿电容配方

### ISSUE THREAD

**Issue by SafariXiu** [Nxer/Twist-Space-Technology-Mod#479]
如图，终极电容到太终极电容都不支持
![24641fbbc5e5452559128beae3b634aa](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/98251218/1de4a2bb-ea71-4d35-8e39-cbfeb368803c)
![62504bc50d774acabaa4a103465a1e81](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/98251218/c813dade-c8df-4a7c-beb8-faad1490ac6d)

**Comment by Nxer** [comment]
是的，勾史配方，狗都不用
