### ISSUE TITLE
在242时启动会卡在百分之66之后未响应

### ISSUE THREAD

**Issue by CCYF78** [Nxer/Twist-Space-Technology-Mod#49]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/150128194/6e108c01-2456-4a43-bc6c-8f1062bc385b)
[minecraft-exported-logs-2023-11-22T01-09-39.log](https://github.com/Nxer/Twist-Space-Technology-Mod/files/13429206/minecraft-exported-logs-2023-11-22T01-09-39.log)

**Comment by Nxer** [comment]
日志没截全，刚好关键信息全部没截到

**Comment by CCYF78** [comment]
[minecraft-exported-logs-2023-11-22T08-38-34.log](https://github.com/Nxer/Twist-Space-Technology-Mod/files/13432286/minecraft-exported-logs-2023-11-22T08-38-34.log)

**Comment by hoshinokiseki** [comment]
把你的gtnh community mod删掉
