### ISSUE TITLE
星核钻机无法启动

### ISSUE THREAD

**Issue by wuyu23** [Nxer/Twist-Space-Technology-Mod#512]
2.6.0使用2.5.0版本tst 星核钻机无法产出矿石 多方块正常成型 基岩也正常放置 启动自动关机

**Comment by Nxer** [comment]
你也知道版本是错的。2.6.0和2.5已停止维护。bug在2.6.1的bartworks里修了。

**Comment by Nxer** [comment]
没给你崩溃不错了
