### ISSUE TITLE
两处文本错误

### ISSUE THREAD

**Issue by Artliuyu4528** [Nxer/Twist-Space-Technology-Mod#518]
于GitHub readme处
`539 * 奇迹定点量子逆变器模式："gtcm.recipe.QuantumInversionRecipes"`
奇迹顶点变成了奇迹定点

于config.java 处
`638         MEG_InfinityEgg_Gen = Long.parseLong(configuration.getString("MEG_InfinityEgg_Gen", MEG, String.valueOf(MEG_InfinityEgg_Gen), "EUt of Crepper eggs, type: long"));`
该条目调整的是无限之蛋，但文本提示为调整爬行者蛋

**Comment by Nxer** [comment]
修了

**Comment by Artliuyu4528** [comment]
> 修了

另外我看抽象之塔文本上写的预热时间是五百秒，但实际在游戏里预热时间是一万秒，每秒仅预热0.01%，翻阅代码后发现这效率值的提升速度现在似乎是和无限之蛋的数量挂钩？希望能在文本内体现

**Comment by Artliuyu4528** [comment]
以及我发现在私人维度中，放下抽象之塔并搭建启动，会显示发电但无实际电量产出，但是如果你将蛋塔所在区块卸载再加载（例如重新进入游戏，或者跑远一点再跑回来），蛋塔就又能正常运作，目前在服务器环境以及单人模式中能够复现

**Comment by Nxer** [comment]
抽象之塔的开发者最近不在线，累计了很多bug了，我有空再看看吧，最近应该不会修

**Comment by Artliuyu4528** [comment]
> 抽象之塔的开发者最近不在线，累计了很多bug了，我有空再看看吧，最近应该不会修

好的
