### ISSUE TITLE
锻炉MK2耗电倍率模块问题

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [Nxer/Twist-Space-Technology-Mod#520]
我也不知道是不是BUG，换上任意模块三录仪都显示耗电倍率100%，其他模块都没这问题
![屏幕截图 2024-07-10 164755](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/a8ee7db7-8c12-4f07-b2eb-e359644c8f94)
![屏幕截图 2024-07-10 164859](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/a2ddf4f7-20c4-47b2-a2c1-5430b502b12a)

**Comment by Nxer** [comment]
似乎是的，我忘了填这部分方法了

**Comment by NNNNMMMMIIII** [comment]
还有个问题，三录仪显示已运行时间永远都是0，没见过涨

**Comment by Nxer** [comment]
> 还有个问题，三录仪显示已运行时间永远都是0，没见过涨

如果全部执行核心都置空则会归零连续运行时间，和你开机关机状态没有关系

**Comment by NNNNMMMMIIII** [comment]
我把东西全扣了就剩主方块，然后跑一些配方还是没涨已运行时间

**Comment by Nxer** [comment]
我一会检查一下

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/3090363a-37aa-4d3e-90cb-5c846bd49db9)

未见异常。你真的运行了吗？不是GUI内说running就是开机，是在跑配方才算运行。
