### ISSUE TITLE
最新版的轻质合金板配方丢失

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [Nxer/Twist-Space-Technology-Mod#525]
以前能一步合成T8的板子
![屏幕截图 2024-07-11 190014](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/cba1e9a4-dec9-468c-9fec-aa4510dbaff4)
![屏幕截图 2024-07-11 190045](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/164090019/b6fd384f-12dc-42e9-a35e-8b6f6e45ed9f)

**Comment by Nxer** [comment]
![__8IN@M557A G{4FD F7)N](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/cdda2d39-33ae-43d6-b45c-51fb97c66687)

草，meta写错了可能
