### ISSUE TITLE
Artificial Star Power Generation

### ISSUE THREAD

**Issue by Zoom6686** [Nxer/Twist-Space-Technology-Mod#537]
![image](https://github.com/user-attachments/assets/f099aaaa-c240-4335-a812-5d6367e307c0)
The currentOutputEU formula is missing the outputMultiplier and rewardContinuous multipliers causing the actual power output to be much lower than displayed on the tooltip/waila.

**Comment by Nxer** [comment]
uh right, I forget that

**Comment by Nxer** [comment]
fixed #538
