### ISSUE TITLE
Machines crash/don't work with new CRIB update

### ISSUE THREAD

**Issue by Niels1006** [Nxer/Twist-Space-Technology-Mod#539]
# Issue
Since 2 weeks or so it is possible for crafting input buffers (crib) to hold more than `int_max` (2.14g) in their inventory.
When they do have more than `int_max` in their inventory, twist multiblocks refuse to do the recipe. See image for the error message.

![image](https://github.com/user-attachments/assets/c25dd0f9-b0d8-419e-802c-9fc2aeae99da)
![image](https://github.com/user-attachments/assets/f4498306-3a2c-4371-8e54-d7c0ed9ecfed)

# Expectation
Twist multis should be able to work with the new cribs update, since its impossible to use twist machines in later stages when crafts exceed `int_max` limit of ingredients.

**Comment by Nxer** [comment]
I see

**Comment by Nxer** [comment]
fix #541
