### ISSUE TITLE
TST0.5.4增强后的戴森球射线接收站使用星阵接受光子数量有误

### ISSUE THREAD

**Issue by CallmeSHaobe** [Nxer/Twist-Space-Technology-Mod#544]
单台最高只能放入16星阵 如若放入再多星阵 接受能量正常 光子产出有误 为1 已确定非OO问题 
![2024-07-22_10 56 08](https://github.com/user-attachments/assets/0dfe36bb-6447-4637-be2d-789bda115e90)

![2024-07-22_10 54 05](https://github.com/user-attachments/assets/50248e0b-a34e-48a7-b234-8238f2fe43af)
![2024-07-22_10 54 30](https://github.com/user-attachments/assets/653d6f33-d186-4e42-9ddc-0c62c8d1a6c8)

**Comment by Nxer** [comment]
让我看看

**Comment by Nxer** [comment]
修了 #547
