### ISSUE TITLE
054闪电尖塔不工作

### ISSUE THREAD

**Issue by Handsonzyx** [Nxer/Twist-Space-Technology-Mod#546]
![QQ截图20240722141129](https://github.com/user-attachments/assets/6f124604-2231-4770-8467-34ba1ce6d556)
![QQ截图20240722141117](https://github.com/user-attachments/assets/3ccd2870-4434-4633-8bba-930cd6f54c23)
![QQ截图20240722141103](https://github.com/user-attachments/assets/1bf8a849-035d-4e7e-8c3d-a55720550e4b)
这套配置是从053延续过来的，更新054之后闪电尖塔就不工作了

**Comment by Handsonzyx** [comment]
emm，主机重放后解决了，神秘

**Comment by Handsonzyx** [comment]
不对，重放之后，每次充电之后主机都提示发生内部错误然后停机

**Comment by Handsonzyx** [comment]
回退053之后正常工作，应该就是054的问题

**Comment by Nxer** [comment]
#548   重写了一下逻辑部分，之前的bug不知道怎么触发的，不过现在正常运行了
