### ISSUE TITLE
261- (430-540)工业注魔压缩太阳能系列配方丢失 服务器

### ISSUE THREAD

**Issue by DearVon2024** [Nxer/Twist-Space-Technology-Mod#551]
430版本时工业注魔压缩太阳能只有压缩太阳能3，合成表为九个压缩太阳能2与普通注魔不同，在按配方加入太阳能后无法进行注魔，显示:小朋友，作业没做完吧 的字样。在服务器相关研究完成与单人测试全解的情况下结尾此情况。在tst版本升级为540时压缩太阳能的工业注魔配方直接消失无法查询（包括先前仅有的错误的压缩太阳能3的合成）。麻烦作者大大解答疑惑，感谢

**Comment by Nxer** [comment]
修了 #549

**Comment by DearVon2024** [comment]
感谢作者大大！
