### ISSUE TITLE
工业显示屏崩档bug

### ISSUE THREAD

**Issue by ThickBlueberryJuice** [Nxer/Twist-Space-Technology-Mod#56]
在群友的亲身经历以及试验下发现，当使用gt传感器扫描戴森球模块的接收器时，将传感器塞进显示屏开机便会崩端，且进存档会到显示屏开机的时间段然后再次崩端（），并且在此bug出现并回档后世界内物品可能会完全重置为原版。

**Comment by q2413274903** [comment]
戴森球射线接收站
