### ISSUE TITLE
奇异物质聚合器吞流体的BUG 锻炉MK2bug

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [Nxer/Twist-Space-Technology-Mod#562]
只要你开机情况下，下线再上线就发现你奇异物质聚合器停机了，维护流体直接变成0，刚刚试了下必定触发这BUG，除非你永远不下线
锻炉MK2 BUG是重启游戏必定会发现结构不形成，退出存档再进去不会触发，只有重启才会

**Comment by Nxer** [comment]
大概是NBT没有保存上
我看一眼

**Comment by Nxer** [comment]
锻炉MK2不成型能排除加载问题吗？所有TST设备均不自带加载区块功能。

**Comment by NNNNMMMMIIII** [comment]
啊这，锻炉确实区块没加载到

**Comment by Nxer** [comment]
> 啊这，锻炉确实区块没加载到

奇异物质聚合器也能排除区块加载的问题吗？

**Comment by Nxer** [comment]
我检查了一下应该不会出这些问题，你先排查一下区块加载导致问题的可能性吧。

**Comment by NNNNMMMMIIII** [comment]
不是区块问题，我200000L蓝框岩浆突然瞬间蒸发，也就做了5000多黑棒，AE也没自动下单做任何东西，后面补了100000l蓝框岩浆也瞬间蒸发，不知道去那里了，AE一滴也不剩

**Comment by Nxer** [comment]
> 不是区块问题，我200000L蓝框岩浆突然瞬间蒸发，也就做了5000多黑棒，AE也没自动下单做任何东西，后面补了100000l蓝框岩浆也瞬间蒸发，不知道去那里了，AE一滴也不剩

你需要隔离你的AE网络然后手动测试是否是奇异物质聚合器的问题，然后再排查确定。

**Comment by NNNNMMMMIIII** [comment]
这bug好难复刻，搞了那么多次才成功了2次，单独AE网络没出现问题，连接主网络就有概率被吞，说了下大致情况
第一次，前脚灌了128000l蓝框岩浆进AE，然后TP到其他星球看戴森球的情况，大概就1分钟左右就tp回去了，就发现AE剩下97000L蓝框岩浆，直接被吞了30000L蓝框岩浆
第二次，重启MC后上来把子网络换成主网络供应蓝框岩浆，然后一启动只剩下3000L蓝框岩浆，原本主网络97000L的蓝框岩浆直接没了
2次都一样情况，AE没下单做东西，没外部储存，没其他子网络

**Comment by Nxer** [comment]
> 这bug好难复刻，搞了那么多次才成功了2次，单独AE网络没出现问题，连接主网络就有概率被吞，说了下大致情况 第一次，前脚灌了128000l蓝框岩浆进AE，然后TP到其他星球看戴森球的情况，大概就1分钟左右就tp回去了，就发现AE剩下97000L蓝框岩浆，直接被吞了30000L蓝框岩浆 第二次，重启MC后上来把子网络换成主网络供应蓝框岩浆，然后一启动只剩下3000L蓝框岩浆，原本主网络97000L的蓝框岩浆直接没了 2次都一样情况，AE没下单做东西，没外部储存，没其他子网络

只说明了问题和机器无关。没有说明问题和机器有关。

**Comment by Nxer** [comment]
确定了问题源了吗
