### ISSUE TITLE
天顶星处理器的配方做不了UXV的材料

### ISSUE THREAD

**Issue by NNNNMMMMIIII** [Nxer/Twist-Space-Technology-Mod#571]
只能产任意UHV电路板，然后磁流体的材料用不了任意UHV电路板，通用电路转也转不了

**Comment by Nxer** [comment]
？什么天顶星处理器，天顶星处理器没配方啊

**Comment by Nxer** [comment]
寰宇处理器UMV UXV级别可以在通用电路板转换器内转换成PIKO电路和量子电路

**Comment by NNNNMMMMIIII** [comment]
直接点天顶星处理器发现有个配方，冲压机做的任意UHV电路
![屏幕截图 2024-07-31 023229](https://github.com/user-attachments/assets/d3e5c9d6-ee4d-4980-9953-09d13a32457e)

**Comment by Nxer** [comment]
没问题，就是这样的
