### ISSUE TITLE
64星阵接收站提供引力透镜后产出异常

### ISSUE THREAD

**Issue by 1Dgrami** [Nxer/Twist-Space-Technology-Mod#572]
未提供时可以正常产出光子，接收能量还在long的范围内，但提供透镜后爆long依然能导致光子不产出的问题
![QQ图片20240731003359](https://github.com/user-attachments/assets/d81a69c7-2e24-4c0b-b8cd-8e005fd2e4b9)
![QQ图片20240731003404](https://github.com/user-attachments/assets/80558d18-8152-4c9f-afaf-4af399771f10)

**Comment by Nxer** [comment]
修了 #573
