### ISSUE TITLE
添加血魔法大机器

### ISSUE THREAD

**Issue by Taskeren** [Nxer/Twist-Space-Technology-Mod#597]
血魔法祭坛，烂！

LE = Life Essence

## 获得 LE

给 #432 里提到的 LEEC (Large Extreme Entity Crusher) 添加一个额外的模式直接产生 LE

产生的 LE 可以直接加到机器脑子里塞的气血宝珠或者输出到输出仓里

## 血魔法配方

做一台大机器来处理血魔法祭坛，炼金术台，还有各种仪式（绑定仪式）的配方

可以消耗机器脑子里塞的气血宝珠里的 LE 或者直接从输入仓里获得 LE

大机器里专门的舱室塞符文能提供速度加成或者 EU 减免

**Comment by Nxer** [comment]
我是麻瓜， @xiaoxing2005  佬救一救
