### ISSUE TITLE
处理矩阵，处理矩阵没了你我可怎么活啊😭

### ISSUE THREAD

**Issue by TheFlames096** [Nxer/Twist-Space-Technology-Mod#6]
*鉴于处理矩阵要被删有感而发*
**量子处理矩阵**
uv级机器
依靠算力运行
**处理矩阵模式**
可放入256台单方块机器
**多方块处理矩阵模式**
需要uhv级能源仓
可放入4台小型多方块机器，需要提供满足其最小结构需求的方块（3* 3* 3-3* 5* 3）
需要额外提供算力（或者别的什么东西？
数值不确定，或许可以多扔几台或者根据提供算力可变

**Comment by TheFlames096** [comment]
鉴于处理矩阵要被删有感而发
量子处理矩阵
uv级机器
依靠算力运行
处理矩阵模式
可放入256台单方块机器
多方块处理矩阵模式
需要uhv级能源仓
可放入4台小型多方块机器，需要提供满足其最小结构需求的方块（3* 3* 3-3* 5* 3）
需要额外提供算力（或者别的什么东西？
数值不确定，或许可以多扔几台或者根据提供算力可变

**Comment by Nxer** [comment]
处理阵列的具体算法恐怕我技术力不够啊

**Comment by foxwhite25** [comment]
这个官方就是因为维护起来太困难才删的（

**Comment by koiNoCirculation** [comment]
大哥阵列来了（
https://github.com/koiNoCirculation/Twist-Space-Technology-Mod/tree/PA
