### ISSUE TITLE
0.5.10梦魇合成中心的一些BUG

### ISSUE THREAD

**Issue by Stulce** [Nxer/Twist-Space-Technology-Mod#626]
工作台配方可以正常缓存。
梦魇工作台配方转换样板存在一些BUG，具体为单倍配方无法正常缓存但是多倍样板可以正常缓存。也并非所有的梦魇工作台配方以倍增方法暂时解决该BUG。
目前我只测试了几样梦魇配方。
阿斯加德蒲公英、无尽之锭等等可以通过倍增样板的方法正常缓存。

基本上所有的太阳能覆盖版，以及传送机、T3微控制器外壳、T3机器人外壳等等，无法通过倍增样板的方法正常缓存。

（双倍星门诶~~）

**Comment by Nxer** [comment]
修了 #627
