### ISSUE TITLE
在2.7.0-nightly-602版本无法正常启动游戏

### ISSUE THREAD

**Issue by AstridDemo** [Nxer/Twist-Space-Technology-Mod#629]
在2.7.0.-nightly-602版本无法正常启动游戏，加载到66%卡死，附crash
[crash-2024-08-25_20.20.37-client.txt](https://github.com/user-attachments/files/16740260/crash-2024-08-25_20.20.37-client.txt)

**Comment by Nxer** [comment]
u兼容nightly

**Comment by PinkYuDeer** [comment]
2.7.0-beta发布了，会进行更新吗QAQ 文明不能没有塔斯听QAQ
