### ISSUE TITLE
me controller 

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#637]
I wanted to propose as an idea a multi-block machine that would replace and make the ae2 controller more efficient, a tier type and each tier adds channels and that adds wireless channels and an input hatch interface that would avoid the use of wireless connectors and only cables would have to be used to connect

**Comment by foxwhite25** [comment]
I don't think it would be possible without a lot of work, you can always just turn off channel entirely, gtnh ae2 have been patched to reduce lag when channel is disabled.
