### ISSUE TITLE
生存模式下构建工业注魔矩阵结构因为信标发生崩溃

### ISSUE THREAD

**Issue by Armelia-William** [Nxer/Twist-Space-Technology-Mod#643]
当蓝图自动放置到信标位置时，发现投影信标的位置呈现红色，无法继续放置方块，如图1。
把信标手动放置在应有的位置后，继续构建多方块结构，随即发生了崩溃，已复现四次

如果手动放置信标后，把挨着信标六个面后续会放置的地方都手动放上，例如图2红色边框
那么不会发生崩溃，多方块会继续构建，直到卡住下一个信标的位置，重复此操作。
![2024-10-08_21 15 28](https://github.com/user-attachments/assets/22ec8c53-30bf-48cf-97d7-9702cd99168c)
![2024-10-08_21 41 16](https://github.com/user-attachments/assets/91a293b4-381a-4464-b5dc-64cefe2ec8f7)
[错误报告-2024-10-8_21.16.17.zip](https://github.com/user-attachments/files/17294273/-2024-10-8_21.16.17.zip)

**Comment by Nxer** [comment]
恐怕无法修复

**Comment by Armelia-William** [comment]
> 恐怕无法修复
好吧，悲伤 :(，不过可以手动先放置好，影响不大。
