### ISSUE TITLE
uhv 

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#645]
Most machines do not accept the offered twist option of the uhv circuits any
![immagine_2024-10-22_092603816](https://github.com/user-attachments/assets/3ad6b10b-c57a-4c5f-89a5-414f4c3ebfb7)

**Comment by Nxer** [comment]
In GTNH 2.6.1 , Electric Implosion Compressor recipes of UXV Magneto component do not support the ANY Circuit. This bug has been fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2809
