### ISSUE TITLE
0.5.11版本的梦魇合成工作中心配方池问题

### ISSUE THREAD

**Issue by TingYu258** [Nxer/Twist-Space-Technology-Mod#651]
只剩下无尽贪婪的25个配方，别的配方池丢失，可以识别工作台配方以及现有的25个配方并合成，不能识别除之以外的终极工作台配方
![EFAD06C4A9AD31F62B8B7C089F73C253](https://github.com/user-attachments/assets/24cf93d5-71f7-4dda-818a-a89ad8285d29)
![96D84CC3502C416BA786EA53ECA532A7](https://github.com/user-attachments/assets/44d7dde7-fefb-44d3-b050-20122e048b4c)
![0C4772644FB85EB8B5CB0CB2C4D734E7](https://github.com/user-attachments/assets/bdf06f82-6c15-441a-a9fa-455e2bbda3bc)
![{8A85E1CF-021F-456b-BB51-DED284DFC003}](https://github.com/user-attachments/assets/97639f5a-1eb1-4898-a7bb-2d7f87800c2d)

**Comment by Xiaohongmao777** [comment]
这25个配方与gtnh原版配方不一样，且这25个配方能通过大梦魇正常合成

**Comment by Nxer** [comment]
![image](https://github.com/user-attachments/assets/c32b8574-e674-452d-9b15-8b7e7d3b9d99)
emm，复现失败

**Comment by Xiaohongmao777** [comment]
> ![image](https://private-user-images.githubusercontent.com/43300390/393750253-c32b8574-e674-452d-9b15-8b7e7d3b9d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzU4NjMsIm5iZiI6MTczMzczNTU2MywicGF0aCI6Ii80MzMwMDM5MC8zOTM3NTAyNTMtYzMyYjg1NzQtZTY3NC00NTJkLTliMTUtOGI3ZTdkM2I5ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA5MTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYjQ0MTYzODA4MWM1OTY5ZTZlM2JjYmE1NWQ0NTZkYzVkNmU5ZTdkMWY0OTgwOGEzNTE2ZDRlYzg2MGUwOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cb2Rg8dcMF9rsVMlvDSgxKH2qouFPkluuFD2rH3_bXY) emm，复现失败

我用原版端加tst0.5.11也没有复现，可能是加的私货的问题

**Comment by Nxer** [comment]
在出现问题时，在启动日志中搜索 “start init extreme craft table recipe”，可能能看到已捕获的终极合成配方数量异常。
大概侦测到原因，可能是静态初始化引起的问题。

**Comment by Nxer** [comment]
#703 修了，应该。
