### ISSUE TITLE
球状闪电的多方块结构有一个方块不对称

### ISSUE THREAD

**Issue by BlueNine9** [Nxer/Twist-Space-Technology-Mod#654]
我正在使用 tst 0.5.11

球状闪电 1 级结构的第 9 层（或 2 级结构的第 31 层）多了一个中子框架，这让本来除了主机附近几乎完全对称的多方块结构变得不对称。我不确定这否是有意为之。

我在试图让两台球状闪电共用结构方块时发现了这一点。如果这里确实多了方块，请修复它。

附图：
2 级结构第 31 层：
![image](https://github.com/user-attachments/assets/d7af6102-b71b-4a19-8c60-88989a0b79d5)
1 级结构第 9 层：
![image](https://github.com/user-attachments/assets/d6bfd72f-bd4b-4048-aeec-d35ff87ff4fe)
整体图：
![image](https://github.com/user-attachments/assets/6a62f13f-f51b-4c34-a2f1-7fee9807f234)

**Comment by Goderium** [comment]
#634 fixed
