### ISSUE TITLE
一些脑洞

### ISSUE THREAD

**Issue by Goderium** [Nxer/Twist-Space-Technology-Mod#66]
宝石加工厂
粉碎机，筛选机，宝石加工厂；定位uev，不需要生物主机，工作时需要持续通入空气。
粉碎机，筛选机：功能同gt++版本。
宝石加工厂：输入矿石或者洗净矿，电路板控制输出粉或其他形态的宝石，机制同top。杀死op的最后一部分，宝石加工模式可以单独给一些特殊材料的配方。

超级冶炼炉
熔炉，合金炉，电弧炉，等离子电弧炉，超级冶炼炉；定位uiv，homo后解锁超级冶炼模式。工作时需要持续通入og，烈焰之炽焰，极寒之凛冰。
熔炉：多配方并行，锁耗时。
合金炉，电弧炉，等离子电弧炉：功能同gt++版本
输入粉末输出锭，机制类似奇迹门。同时有部分高级配方，如超立方体或者uxv+材料。
（可以拆分部分炉子为两台机器）

超级组装机
组装机，精密组装机，超级组装机；定位uxv，无法升压，升级某个部件解锁max电压。
组装机，精密组装机：多配方并行，锁耗时。
实现装配线功能，或者部分装配线配方，如线圈，外壳等。可以的话读取闪存
超级组装模式，用于组装uxv+机器或者max部件等（工作效率与纳米蜂群有关，或者消耗纳米蜂群）

巨浸洗，脱水；定位uhv
巨酿造，流体加热；定位umv

**Comment by Nxer** [comment]
- 熔炉需要242发布后换官方并行计算器，因为有大量矿辞配方。
 - 高炉预计在奇迹之门的第二个模式。
 - 其他冶炼设备待定，或者你来写。
 - 组装机暂时没有计划，只准备给精密组装机多几个等级的结构方块。
 - 其他待定。

**Comment by Goderium** [comment]
等我出门就来学怎么写（）
