### ISSUE TITLE
一个潜在问题？ 空间缩放能无视需要稳定的黑洞/HIP装置的条件

### ISSUE THREAD

**Issue by Keriils** [Nxer/Twist-Space-Technology-Mod#662]
这个问题应该算是bug?
可以执行HIP 我个人觉得还行(
如果执行黑洞感觉太超模了 比如蓝框岩浆的超致密板子
![image](https://github.com/user-attachments/assets/249f8bd9-f63c-41bf-b18b-21455d672894)
![image](https://github.com/user-attachments/assets/1816d261-a072-478e-8eee-79386696b4b6)

**Comment by Nxer** [comment]
属于未进行适配的部分
