### ISSUE TITLE
miracle door

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#669]
miracle door void item at random but have energy and item 
![image](https://github.com/user-attachments/assets/c82a7b01-f7cd-48e5-bc8d-a8ec196cc376)

**Comment by horobo** [comment]
i post down the link of the video https://convertio.co/it/download/bd670b735d0b2c19a1a343498548d7061a6bf7/

**Comment by Goderium** [comment]
is there any critical photon?

**Comment by horobo** [comment]
Nope

**Comment by Goderium** [comment]
refer to the second page of the tooltip

**Comment by horobo** [comment]
Its only for alloy blast smelter mode

**Comment by horobo** [comment]
ok it works but it doesn't make liquids but it makes ingots

**Comment by horobo** [comment]
ty i resolve
