### ISSUE TITLE
Allow Sharing of the Molecular Coils on the Hephaestus Atelier Multi

### ISSUE THREAD

**Issue by srdr2k3** [Nxer/Twist-Space-Technology-Mod#672]
Currently it is not possible to wall share the Hephaestus Atelier due to the 2 heat proof casings. The Image is an example of what it should be changed to so it allows a cool wall shared design.
![image](https://github.com/user-attachments/assets/64e0a875-d539-4d45-84fc-f859a1d80c73)

This is a super critical issue!!!!

**Comment by srdr2k3** [comment]
![image](https://github.com/user-attachments/assets/177e7225-177d-4502-82f1-5a9fd594a361)
Imagine a world with this structure!!

**Comment by Nxer** [comment]
This will destroy the overall harmony of the structure.
