### ISSUE TITLE
270版本下任意电路相关问题

### ISSUE THREAD

**Issue by maple-9945** [Nxer/Twist-Space-Technology-Mod#678]
在270版本中通用电路板转换器会将UMV和UXV级别的电路转化为对应的任意电路（在261时会转化为piko和量子电路），而在巨型装配线，奇迹顶点等由tst添加的某些配方依旧只能使用piko电路或量子电路，建议更新一下某些相关物品配方（将只能使用piko电路或者量子电路更改为任意umv或uxv电路）。（从粗制到鸿蒙等级的鸿蒙之眼结构方块都存在该问题，且不可视之触，球状闪电芯片等配方也存在该问题）

**Comment by Goderium** [comment]
#655
