### ISSUE TITLE
Some more multiblocks

### ISSUE THREAD

**Issue by MaGeBZz** [Nxer/Twist-Space-Technology-Mod#70]
Saw the mod and love the idea
While getting stargate in "normal NH" I added this mod in another instance

Got some ideas for more multiblocks that need a "better version" eventually

I could think of:
- EBF/Mega EBF new multi
- Vacuum Freezer/Mega VF new multi
- Better multi for fusion (even 20x mk5 compact is slow in endgame - maybe not adding a mk6 more like a multi that fits better to endgame imo)
- Some assline alternative (cause data banks etc are pretty outdated imo or a wireless data bank to make assline recipes not that bad anymore)

If I can think about more I will make a new issue

**Comment by MaGeBZz** [comment]
Maybe there could be something like a better version of the multi smelter too
It's not a huge bottleneck in endgame but would be nice to have a multi that fits more in endgame for normal smelting too

**Comment by Nxer** [comment]
- EBF - Freezer is already in plan.
- Fusion has not, maybe we need to change the mind to get the plasma resource , not only the classic fusion method.
- Assembler Line is also, the concept of mechanical assembly is too outdated for the late stages of the game. So I'll try to separate the basic assembler line recipe and set it into other styles.

**Comment by Nxer** [comment]
Larger smelter will be added when GTNH update to 2.4.2 stable version.
I rewrite the parallel calculator to fit the big number of parallel, but the new calculator can not process Ore Dict inputs.
GTNH has also rewrite the calculator in test version, and fix the bug.
So wait it update.

**Comment by MaGeBZz** [comment]
> > Is there a discord for the mod here eventually @Nxer ?
> 
> No, emmm, we use QQ as usual and directly chat in normal GTNH channel

Fair just wanted to be sure
Btw if I got more ideas for multis should I make a new issue or just post it here? Thought about a UU-Matter generation multi rn too
