### ISSUE TITLE
奇迹顶点无损超频失效

### ISSUE THREAD

**Issue by Goderium** [Nxer/Twist-Space-Technology-Mod#73]
![2(FL%0RG@W)Z5L7317$BAWU](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/b5faa361-27f5-4e4a-bc95-cea8b7aedf14)
![1}T5{I)ZE C _`7 F_2%ZRN](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/b42eb48c-7039-499b-ae84-4b3216b9f94d)
超频七次，预计耗时30s，实际30x2^7=3840s
![89UOA3IE6%TSNES7DY()2VH](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/306f744d-03e1-4526-83c8-1c83151345c6)
![XRP82IA$J26R%6Y$RJ_CF_S](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/02aef7a8-7b4f-4bb4-ad0e-7953d5ade448)
超频1次，预计耗时8.45s，实际8.45x2=16.9s

**Comment by Nxer** [comment]
修复了
