### ISSUE TITLE
真的修了吗？如修。

### ISSUE THREAD

**Issue by hoshinokiseki** [Nxer/Twist-Space-Technology-Mod#75]
通用矿物处理厂TST依然会将某些矿物视作非矿石输入物。见图。物品ID后补。
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/88672077/cd8b7821-06c9-4892-a17c-b2a10b33e42d)

**Comment by Nxer** [comment]
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/43300390/4a7b97ff-2670-498b-b484-ad8835105fd7)

**Comment by Nxer** [comment]
770， 817， 871， 920   没加进去，别的应该都处理了
