### ISSUE TITLE
空间缩放仪-回旋加速器模式产氢等离子时出现空指针

### ISSUE THREAD

**Issue by Sun0Pig** [Nxer/Twist-Space-Technology-Mod#82]
GTNH - ver : 2.4.0; gregtech - ver : 5.09.44.03; TST - ver : 0.3.0
空间缩放仪配置：粗制稳定力场发生器、64a UEV无线能源仓
       编程电路：21
       输入物品：氢离子
       输入流体：氢气
配方如图：
![recipe](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/121376738/4cda2320-d462-4a41-913c-5a50f8c1dbcf)
机器内GUI如图：
![GUI](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/121376738/6715f42a-a3e1-42c0-ab1f-410c4f42020a)
服务端日志如图：
![log](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/121376738/306e7e7f-f37d-46b0-ad87-4e416d3821da)

**Comment by Nxer** [comment]
#86 修了
