### ISSUE TITLE
不兼容服务端（只是尝试）

### ISSUE THREAD

**Issue by ruoji1234** [Nxer/Twist-Space-Technology-Mod#96]
[crash-2023-12-08_23.06.16-server.txt](https://github.com/Nxer/Twist-Space-Technology-Mod/files/13615692/crash-2023-12-08_23.06.16-server.txt)
启动服务端即崩溃，forge官端

**Comment by Nxer** [comment]
什么版本，GT的枚举类被删除了导致的错误
下个版本我在mod内部复制这些枚举信息吧

**Comment by ruoji1234** [comment]
版本是2.4.1

**Comment by ruoji1234** [comment]
模组版本是0.3.1

**Comment by Nxer** [comment]
不知道什么问题，错误报告指出的地方近期是没有做过修改的。不应该出现这个错误才对
