### ISSUE TITLE
mini mixer bug 

### ISSUE THREAD

**Issue by horobo** [Nxer/Twist-Space-Technology-Mod#98]
the mixer does not do the actual speed mentioned, but it does a maximum of 3 even though it can do 2048 in parallel

**Comment by Goderium** [comment]
![0 ETGI{(` UQ)D)85PG~~ZO](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/58ef3b9a-2859-42cd-8f72-d6752a9a5629)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/3be2ed56-fc11-4d27-882b-60ea9c33c4d2)
![image](https://github.com/Nxer/Twist-Space-Technology-Mod/assets/143515349/b6cdac73-93a7-4b4f-b8ca-525aaf7118ee)

Such as this recipe in 65536A UXV, 8192 parallel
The time multiplier is 0.8^13=0.0549, 
The OC Times is lg(65536*UXV/ZPM/8192)/lg(4)=7.5,
The actual time consumption is 2500*0.0549/2^7=1.0723
It seems to be no problem

**Comment by horobo** [comment]
> More details? what recipe , input bus / hatch , output bus / hatch , energy hatch ? and what the WAILA info show

Raw neutronium dust input buffer bus output bus me uiv wireless hatch and 11,25 second zpm

**Comment by Nxer** [comment]
> Raw neutronium dust input buffer bus output bus me uiv wireless hatch and 11,25 second zpm

I'll try to reappear it.
